### ISSUE TITLE
No such file or directory: './frames/frame.jpg'

### ISSUE THREAD

**Issue by ciccarone** [cbh123/narrator#1]
capture.py seems to be capturing the images (webcam is on, console repeating "Say Cheese"

However when running narrator.py in a different terminal, I am getting an error message saying that frames/frame.jpg doesn't exist

I do not see this directory or files

**Comment by andre15silva** [comment]
You have to create the directory "frames" before running the script. It does not create it by itself.

**Comment by mattm** [comment]
I created a PR to fix this (#7) this issue since I ran into it as well.

**Comment by ciccarone** [comment]
Oh!  Thanks @mattm and @andre15silva
