### ISSUE TITLE
uhm, just a noob who needs help

### ISSUE THREAD

**Issue by noaheng1** [cbh123/narrator#16]
What python version do i need for this? 

Simple audio needs 3.8 but i found that another module required 3.9 so i was not able to get it running. Any help is greatly appreciated.

**Comment by mauckc** [comment]
@noaheng1 Are you building the venv on a mac? I think this simpleaudio build issue is OS related.
https://stackoverflow.com/questions/63972113/big-sur-clang-invalid-version-error-due-to-macosx-deployment-target

**Comment by noaheng1** [comment]
I was able to solve it! Took me a while to realize this guide was meant for MAC users. I edited the "requirements" txt and it solved my issue! 

Thanks for trying to help though :)
