### ISSUE TITLE
Simple guide

### ISSUE THREAD

**Issue by canalman** [cbh123/narrator#22]
This is a very cool project. .... is there a complete step by step guide for this as all the additional bits to set up Replicate, voice in Elevenlab etc have lost me a bit...

🤞🤘

**Comment by contentfree** [comment]
You should be able to follow the steps in the readme and get there. The only hurdle is finding an Attenborough-like voice in Elevenlabs (though #3 provides a link to an MP3 that can be used for Instant Voice Cloning at Elevenlabs (which requires the Starter plan, I believe). 

The prerequisites are an OpenAI API account (with available credits…) and an Elevenlabs account on at least the Starter plan.

@cbh123 Do you want to review the guide in the readme so you can close this ticket?

**Comment by cbh123** [comment]
I'll try and find time to make it a bit more clear, but in the mean time there's also a high level blog post explaining the ideas: https://replicate.com/blog/how-to-create-an-ai-narrator. Hope this helps!
