### ISSUE TITLE
gpt-4-vision-preview` does not exist 

### ISSUE THREAD

**Issue by moorlag** [cbh123/narrator#25]
After using the install methode and adding the API keys I receive this error. 

👀 David is watching...

The model `gpt-4-vision-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

**Comment by shashank-shekher** [comment]
> After using the install methode and adding the API keys I receive this error.
> 
> 👀 David is watching...
> 
> The model `gpt-4-vision-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

Exactly the same error for me. This issue is closed by @moorlag , Were you able to resolve the issue @moorlag?

**Comment by shashank-shekher** [comment]
For those who are interested- 
If you see this error, please check your API billing status. Note that chatgpt Plus account is different from OpenAI API account.

In my case, I had the Plus account so I was under the impression (reading documentation) that I can reach all models, not to be.

**Comment by mauckc** [comment]
Currently, even if you have a paid account you need to have paid a minimum of $1 to have access to the latest models.

**Comment by prolificcoder** [comment]
I had paid account for few months and paid subscription fees, is there a different payment this error is talking about?

**Comment by shashank-shekher** [comment]
> I had paid account for few months and paid subscription fees, is there a different payment this error is talking about?
@prolificcoder With ChatGPT Plus subscription, you don't get access to **gpt-4-vision-preview**. For OpenAI's API, you need to make payment to GPT-4 API as mentioned [in the FAQ](https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4). 

After logging into OpenAI's account, go to [https://platform.openai.com/usage]( https://platform.openai.com/usage), you can see your usage details, it should be more than $1. I would suggest pre-paying the minimum $5 and then use API as pay-per-request.

**Comment by prolificcoder** [comment]
> > I had paid account for few months and paid subscription fees, is there a different payment this error is talking about?
> 
> @prolificcoder With ChatGPT Plus subscription, you don't get access to **gpt-4-vision-preview**. For OpenAI's API, you need to make payment to GPT-4 API as mentioned [in the FAQ](https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4).
> 
> After logging into OpenAI's account, go to https://platform.openai.com/usage, you can see your usage details, it should be more than $1. I would suggest pre-paying the minimum $5 and then use API as pay-per-request.

Yes, that worked for me and we had fun with it. Thank you!
