### ISSUE TITLE
Blank image from capture

### ISSUE THREAD

**Issue by jakeboyles** [cbh123/narrator#5]
I am getting a weird blank image from capture. Not what is actually from my webcam and my webcam is not activated during. Any ideas?
![frame](https://github.com/cbh123/narrator/assets/2816632/04846e25-648e-43d4-8b6c-c4dd61c1b263)

**Comment by jakeboyles** [comment]
Turns out I have multiple cameras on macOS. It was reading my phones camera in my pocket. 

cap = cv2.VideoCapture(2)

Changing that fixed it.

**Comment by mrpher** [comment]
@jakeboyles good find, had the same issue. For me though it was `cap = cv2.VideoCapture(2)` on a Macbook Air M2.
